### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by bhuezodd** [JSebasART/GpReact#1]
You are not sending username and password on login, please fix ASAP
![image](https://user-images.githubusercontent.com/61662634/145074720-bf9bea41-45fb-4976-97b1-2050f41140ac.png)

**Comment by stevenbdf** [comment]
Same here :(

**Comment by stevenbdf** [comment]
😡😡😡

**Comment by stevenbdf** [comment]
Don't close issues that are not resolved, the problem persists. 

Please fix it
